-- Run these commands in the Supabase SQL Editor

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    sid TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'student',
    status TEXT DEFAULT 'approved',
    department TEXT,
    semester TEXT,
    section TEXT,
    photo_path TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Subjects Table
CREATE TABLE IF NOT EXISTS subjects (
    subject_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_name TEXT NOT NULL,
    class_name TEXT NOT NULL,
    added_by TEXT REFERENCES users(sid) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Attendance Sessions
CREATE TABLE IF NOT EXISTS attendance_sessions (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id TEXT REFERENCES users(sid) ON DELETE CASCADE,
    subject_id BIGINT REFERENCES subjects(subject_id) ON DELETE CASCADE,
    subject TEXT NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    end_time TIMESTAMP WITH TIME ZONE,
    active BOOLEAN DEFAULT TRUE,
    session_name TEXT,
    session_date TEXT,
    department TEXT,
    semester TEXT,
    section TEXT
);

-- 4. Valid Tokens (for QR codes)
CREATE TABLE IF NOT EXISTS valid_tokens (
    token TEXT PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 5. Attendance Records
CREATE TABLE IF NOT EXISTS attendance_records (
    record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT REFERENCES attendance_sessions(session_id) ON DELETE CASCADE,
    sid TEXT REFERENCES users(sid) ON DELETE CASCADE,
    name TEXT NOT NULL,
    subject_id BIGINT REFERENCES subjects(subject_id) ON DELETE SET NULL,
    subject TEXT NOT NULL,
    date TEXT NOT NULL,
    time TEXT NOT NULL,
    status TEXT DEFAULT 'present',
    marked_type TEXT DEFAULT 'qr',
    marked_by TEXT REFERENCES users(sid) ON DELETE SET NULL,
    UNIQUE(session_id, sid)
);

-- 6. Insert Default Admin
INSERT INTO users (sid, name, password, role)
VALUES ('admin', 'Administrator', 'admin123', 'admin')
ON CONFLICT (sid) DO NOTHING;
